#!/usr/bin/env bash
#
#   - Creates the file /var/run/myscript.pid containing its PID
#   - Displays To infinity and beyond indefinitely
#   - Displays I hate the kill command when receiving a SIGTERM signal
#   - Displays Y U no love me?! when receiving a SIGINT signal
#   - Deletes the file /var/run/my script.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

PRID=$$
echo "$PRID" > /var/run/myscript.pid

function love_script()
{
    echo "Y U no love me?!"
}

function Quit()
{
    echo "I hate the kill command"
    rm -f /var/run/myscript.pid
    kill -9 $PRID
}

trap love_script SIGINT
trap Quit SIGQUIT SIGTERM

while :
do
    echo "To infinity and beyond"
    sleep 2
done

